// Copyright (c) 2023 Brett Curtis
#ifndef TokensH
#define TokensH
enum TToken
{
   OPcomma      ,
   OPthrow      ,
   OPapply      ,

   OPassign     ,
   OPmul_assign ,
   OPdiv_assign ,
   OPmod_assign ,
   OPadd_assign ,
   OPsub_assign ,
   OPand_assign ,
   OPor_assign  ,
   OPxor_assign ,
   OPcat_assign ,
   OPshl_assign ,
   OPshr_assign ,
   OPusr_assign ,

   OPcond_quest ,

   OPor_bool    ,

   OPand_bool   ,

   OPor_bit     ,

   OPxor_bit    ,

   OPand_bit    ,

   OPequal      ,
   OPnot_equal  ,

   OPless       ,
   OPless_equal ,
   OPmore       ,
   OPmore_equal ,
   OPshl        ,
   OPshr        ,
   OPusr        ,

   OPcat        ,
   OPcons       ,

   OPadd        ,
   OPsub        ,

   OPmul        ,
   OPdiv        ,
   OPmod        ,

   OPpow        ,

   OPptr_mem    ,
   OPptr_mem_ptr,

   OPnot_bool   ,
   OPnot_bit    ,
   OPadd_unary  ,
   OPsub_unary  ,
   OPinc_pre    ,
   OPdec_pre    ,
   OPinc_post   ,
   OPdec_post   ,
   OPref        ,
   OPderef      ,

   OPtemplate   ,
   OPfunc       ,
   OPindex      ,
   OPmem_ptr    ,
   OPscope      ,
   OPmem        ,

   OPgetElem    ,

	TOKvoid         ,

	TOKbool         ,
	TOKbit          ,
	TOKbyte			 ,
	TOKubyte        ,
	TOKshort        ,
	TOKushort       ,
	TOKint			 ,
	TOKuint         ,
	TOKlong         ,
	TOKulong        ,
	TOKcent         ,
	TOKucent        ,
	TOKfloat        ,
	TOKdouble       ,
	TOKreal         ,
	TOKcfloat       ,
	TOKcdouble      ,
	TOKcreal        ,
	TOKidouble      ,
	TOKifloat       ,
	TOKireal        ,
	TOKchar         ,
	TOKwchar        ,
	TOKdchar        ,

	TOKarray        ,
	TOKclass        ,
	TOKdelegate     ,
	TOKenum         ,
	TOKfunction     ,
	TOKpointer      ,
	TOKstruct       ,
	TOKtypedef      ,
	TOKunion        ,

	TOKprivate      ,
	TOKpackage      ,
	TOKprotected    ,
	TOKpublic       ,
   TOKpublished    ,

	TOKconst        ,
	TOKfinal        ,
	TOKdeprecated   ,
	TOKexport       ,
	TOKstatic       ,
	TOKoverride     ,
	TOKabstract     ,
	TOKauto         ,

	TOKalias        ,
	TOKalign        ,
	TOKasm          ,
	TOKassert       ,
	TOKbody         ,
	TOKbreak        ,
	TOKcase         ,
	TOKcast         ,
	TOKcatch        ,
	TOKcontinue     ,
	TOKdebug        ,
	TOKdefault      ,
	TOKdelete       ,
	TOKdo           ,
	TOKelse         ,
	TOKextern       ,
	TOKfalse        ,
	TOKfinally      ,
	TOKfor          ,
	TOKforeach      ,
	TOKgoto         ,
	TOKif           ,
	TOKimport       ,
	TOKin           ,
	TOKinout        ,
	TOKinterface    ,
	TOKinvariant    ,
	TOKis           ,
	TOKmixin        ,
	TOKmodule       ,
	TOKnew          ,
	TOKnullptr         ,
	TOKout          ,
	TOKpragma       ,
	TOKreturn       ,
	TOKsuper        ,
	TOKswitch       ,
	TOKsynchronized ,
	TOKtemplate     ,
	TOKthis         ,
	TOKthrow        ,
	TOKtrue         ,
	TOKtry          ,
	TOKtypeid       ,
	TOKtypeof       ,
	TOKunittest     ,
	TOKversion      ,
	TOKvolatile     ,
	TOKwhile        ,
	TOKwith         ,

	TOKblock			 ,
	TOKvar			 ,
	TOKtemplate_args
};
#endif
